# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/kria_bd/kria_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd || ORIG_REF_NAME==kria_bd} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_zynq_ultra_ps_e_0_0/kria_bd_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_bd_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_clk_wiz_0_0/kria_bd_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_clk_wiz_0_0 || ORIG_REF_NAME==kria_bd_clk_wiz_0_0} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_proc_sys_reset_0_0/kria_bd_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==kria_bd_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_proc_sys_reset_1_0/kria_bd_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_1_0 || ORIG_REF_NAME==kria_bd_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_axi_intc_0_0/kria_bd_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_axi_intc_0_0 || ORIG_REF_NAME==kria_bd_axi_intc_0_0} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_ps8_0_axi_periph_0/kria_bd_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_ps8_0_axi_periph_0 || ORIG_REF_NAME==kria_bd_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/kria_bd/ip/kria_bd_auto_pc_0/kria_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==kria_bd_auto_pc_0 || ORIG_REF_NAME==kria_bd_auto_pc_0} -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_zynq_ultra_ps_e_0_0/kria_bd_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_zynq_ultra_ps_e_0_0/kria_bd_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==kria_bd_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_clk_wiz_0_0/kria_bd_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_clk_wiz_0_0 || ORIG_REF_NAME==kria_bd_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_clk_wiz_0_0/kria_bd_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_clk_wiz_0_0 || ORIG_REF_NAME==kria_bd_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_clk_wiz_0_0/kria_bd_clk_wiz_0_0_ooc.xdc

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_proc_sys_reset_0_0/kria_bd_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==kria_bd_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_proc_sys_reset_0_0/kria_bd_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_0_0 || ORIG_REF_NAME==kria_bd_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_proc_sys_reset_1_0/kria_bd_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_1_0 || ORIG_REF_NAME==kria_bd_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_proc_sys_reset_1_0/kria_bd_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_proc_sys_reset_1_0 || ORIG_REF_NAME==kria_bd_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_intc_0_0/kria_bd_axi_intc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_axi_intc_0_0 || ORIG_REF_NAME==kria_bd_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_intc_0_0/kria_bd_axi_intc_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==kria_bd_axi_intc_0_0 || ORIG_REF_NAME==kria_bd_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_axi_intc_0_0/kria_bd_axi_intc_0_0_ooc.xdc

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/ip/kria_bd_auto_pc_0/kria_bd_auto_pc_0_ooc.xdc

# XDC: /home/rafael/vivado_projects/kria_kr260/kria_kr260.gen/sources_1/bd/kria_bd/kria_bd_ooc.xdc
